#!/bin/bash
set -e

unlink $(which python)
ln -s $(which python3) /usr/local/bin/python
git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.12.0
. "$HOME/.asdf/asdf.sh"
source ~/.bashrc
asdf plugin-add python
asdf install python $1
asdf global python $1
