## Use whatever base image
FROM alpine

# https://github.com/ufoscout/docker-compose-wait/releases/
ARG ARG_COMPOSE_WAIT_VER=2.9.0

## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/${ARG_COMPOSE_WAIT_VER}/wait /wait

RUN chmod +x /wait

CMD ["/wait"]
